package com.mapper;

import com.entity.Consumption;
import com.entity.ConsumptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConsumptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbggenerated
     */
    int countByExample(ConsumptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbggenerated
     */
    int deleteByExample(ConsumptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbggenerated
     */
    int insert(Consumption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbggenerated
     */
    int insertSelective(Consumption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbggenerated
     */
    List<Consumption> selectByExample(ConsumptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbggenerated
     */
    Consumption selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Consumption record, @Param("example") ConsumptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Consumption record, @Param("example") ConsumptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Consumption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Consumption record);
}