package entity;

import java.util.Date;

public class Consumption {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption.machine_id
     *
     * @mbggenerated
     */
    private Integer machineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumption.fee
     *
     * @mbggenerated
     */
    private String fee;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption
     *
     * @mbggenerated
     */
    public Consumption(Integer id, Integer userId, Integer machineId, Date addTime, Date endTime, String fee) {
        this.id = id;
        this.userId = userId;
        this.machineId = machineId;
        this.addTime = addTime;
        this.endTime = endTime;
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption.id
     *
     * @return the value of consumption.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption.user_id
     *
     * @return the value of consumption.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption.machine_id
     *
     * @return the value of consumption.machine_id
     *
     * @mbggenerated
     */
    public Integer getMachineId() {
        return machineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption.add_time
     *
     * @return the value of consumption.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption.end_time
     *
     * @return the value of consumption.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumption.fee
     *
     * @return the value of consumption.fee
     *
     * @mbggenerated
     */
    public String getFee() {
        return fee;
    }
}